"""
Generate an MQL5 script to plot S97 backtest trades (2025-2026) on Exness MT5 charts.

The Python MT5 library does NOT support chart object drawing—that requires MQL5.
This script:
  1. Reads s97_all_pairs_trades.json
  2. Filters trades from 2025 and 2026
  3. Generates a .mq5 script file with ObjectCreate calls
  4. Copies it to the MT5 Scripts folder

Usage:
  python scripts/plot_s97_trades_on_mt5.py
  python scripts/plot_s97_trades_on_mt5.py --pair GBPUSD     # one pair only
  python scripts/plot_s97_trades_on_mt5.py --clear            # generate clear-only script
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

# ─── paths ───────────────────────────────────────────────────────────────────
HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
TRADES_JSON = ROOT / "docs" / "s97_all_pairs_trades.json"
OUTPUT_DIR = ROOT / "scripts" / "mql5_output"

# ─── config ──────────────────────────────────────────────────────────────────
PREFIX = "S97_"


def dt_to_mql5(iso_str: str) -> str:
    """Convert ISO datetime string to MQL5 datetime literal: D'YYYY.MM.DD HH:MM'"""
    dt = datetime.fromisoformat(iso_str).astimezone(timezone.utc)
    return f"D'{dt.strftime('%Y.%m.%d %H:%M')}'"


def generate_mql5_script(filtered: dict[str, list], clear_only: bool = False) -> str:
    """Generate full MQL5 script source code."""
    lines = []

    lines.append("//+------------------------------------------------------------------+")
    lines.append("//| PlotS97Trades.mq5  —  Auto-generated by plot_s97_trades_on_mt5.py |")
    lines.append("//|  Plots S97 backtest trades (2025-2026) on all pair charts          |")
    lines.append("//+------------------------------------------------------------------+")
    lines.append('#property copyright "S97 Trade Plotter"')
    lines.append('#property version   "1.00"')
    lines.append('#property script_show_inputs')
    lines.append("")
    lines.append("// ─── Color definitions (BGR) ──────────────────────────────────────")
    lines.append("#define CLR_WIN_ENTRY    clrForestGreen")
    lines.append("#define CLR_WIN_LINE     clrLimeGreen")
    lines.append("#define CLR_LOSS_ENTRY   clrCrimson")
    lines.append("#define CLR_LOSS_LINE    clrRed")
    lines.append("#define CLR_SL           clrOrangeRed")
    lines.append("#define CLR_TP           clrDodgerBlue")
    lines.append("#define CLR_EXIT_WIN     clrGold")
    lines.append("#define CLR_EXIT_LOSS    clrSalmon")
    lines.append("#define CLR_ZONE_WIN     C'34,170,34'")
    lines.append("#define CLR_ZONE_LOSS    C'200,50,50'")
    lines.append("")
    lines.append("input bool ClearOnly = false;  // Only clear existing objects")
    lines.append("")

    # ── Helper functions ──
    lines.append("//+------------------------------------------------------------------+")
    lines.append("void DrawTrendLine(long chart, string name, datetime t1, double p1,")
    lines.append("                   datetime t2, double p2, color clr, int width=2,")
    lines.append("                   ENUM_LINE_STYLE style=STYLE_SOLID, bool back=true)")
    lines.append("{")
    lines.append("   ObjectDelete(chart, name);")
    lines.append("   ObjectCreate(chart, name, OBJ_TREND, 0, t1, p1, t2, p2);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_COLOR, clr);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_WIDTH, width);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_STYLE, style);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_RAY_RIGHT, false);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_RAY_LEFT, false);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_BACK, back);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_SELECTABLE, false);")
    lines.append("}")
    lines.append("")
    lines.append("//+------------------------------------------------------------------+")
    lines.append("void DrawArrow(long chart, string name, datetime t, double price,")
    lines.append("               color clr, int code=233, int sz=2)")
    lines.append("{")
    lines.append("   ObjectDelete(chart, name);")
    lines.append("   ObjectCreate(chart, name, OBJ_ARROW, 0, t, price);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_ARROWCODE, code);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_COLOR, clr);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_WIDTH, sz);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_SELECTABLE, false);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_BACK, false);")
    lines.append("}")
    lines.append("")
    lines.append("//+------------------------------------------------------------------+")
    lines.append("void DrawRect(long chart, string name, datetime t1, double p1,")
    lines.append("              datetime t2, double p2, color clr, bool fill=true)")
    lines.append("{")
    lines.append("   ObjectDelete(chart, name);")
    lines.append("   ObjectCreate(chart, name, OBJ_RECTANGLE, 0, t1, p1, t2, p2);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_COLOR, clr);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_FILL, fill);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_BACK, true);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_SELECTABLE, false);")
    lines.append("}")
    lines.append("")
    lines.append("//+------------------------------------------------------------------+")
    lines.append("void DrawText(long chart, string name, datetime t, double price,")
    lines.append("              string text, color clr, int fontSize=8)")
    lines.append("{")
    lines.append("   ObjectDelete(chart, name);")
    lines.append("   ObjectCreate(chart, name, OBJ_TEXT, 0, t, price);")
    lines.append("   ObjectSetString(chart, name, OBJPROP_TEXT, text);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_COLOR, clr);")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_FONTSIZE, fontSize);")
    lines.append("   ObjectSetString(chart, name, OBJPROP_FONT, \"Arial Bold\");")
    lines.append("   ObjectSetInteger(chart, name, OBJPROP_SELECTABLE, false);")
    lines.append("}")
    lines.append("")

    # ── Clear function ──
    lines.append("//+------------------------------------------------------------------+")
    lines.append("void ClearS97Objects(long chart)")
    lines.append("{")
    lines.append('   int total = ObjectsTotal(chart, 0, -1);')
    lines.append("   for(int i = total - 1; i >= 0; i--)")
    lines.append("   {")
    lines.append('      string name = ObjectName(chart, i);')
    lines.append(f'      if(StringFind(name, "{PREFIX}") == 0)')
    lines.append("         ObjectDelete(chart, name);")
    lines.append("   }")
    lines.append("}")
    lines.append("")

    # ── Per-pair plot function ──
    lines.append("//+------------------------------------------------------------------+")
    lines.append("long OpenOrFindChart(string symbol)")
    lines.append("{")
    lines.append("   // Try to find existing chart")
    lines.append("   long chart = ChartFirst();")
    lines.append("   while(chart >= 0)")
    lines.append("   {")
    lines.append("      if(ChartSymbol(chart) == symbol)")
    lines.append("      {")
    lines.append("         ChartSetSymbolPeriod(chart, symbol, PERIOD_H4);")
    lines.append("         return chart;")
    lines.append("      }")
    lines.append("      chart = ChartNext(chart);")
    lines.append("   }")
    lines.append("   // Open new chart")
    lines.append("   chart = ChartOpen(symbol, PERIOD_H4);")
    lines.append("   if(chart > 0) Sleep(500);")
    lines.append("   return chart;")
    lines.append("}")
    lines.append("")

    # ── Per-pair trade plotting functions ──
    for pair, trades in filtered.items():
        func_name = f"PlotTrades_{pair}"
        lines.append("//+------------------------------------------------------------------+")
        lines.append(f"void {func_name}(long chart)")
        lines.append("{")

        for trade in trades:
            tn = trade["trade_number"]
            direction = trade["direction"]
            entry_price = trade["entry_price"]
            sl = trade["stop_loss"]
            tp = trade["take_profit"]
            exit_price = trade["exit_price"]
            outcome = trade["outcome"]
            pnl = trade["pnl_R"]

            entry_dt = dt_to_mql5(trade["entry_time"])
            exit_dt = dt_to_mql5(trade["exit_time"])

            is_win = outcome == "win"
            base = f"{PREFIX}{pair}_T{tn:03d}"

            clr_line = "CLR_WIN_LINE" if is_win else "CLR_LOSS_LINE"
            clr_entry = "CLR_WIN_ENTRY" if is_win else "CLR_LOSS_ENTRY"
            clr_exit = "CLR_EXIT_WIN" if is_win else "CLR_EXIT_LOSS"
            clr_zone = "CLR_ZONE_WIN" if is_win else "CLR_ZONE_LOSS"

            arrow_entry = 233 if direction == "long" else 234  # up / down arrow
            dir_char = "L" if direction == "long" else "S"
            label = f"#{tn} {dir_char} {pnl:+.2f}R"

            lines.append(f"   // ── Trade #{tn} ({direction} | {outcome} | {pnl:+.2f}R) ──")

            # Entry→Exit trade line
            lines.append(f'   DrawTrendLine(chart, "{base}_TRADE", {entry_dt}, {entry_price}, {exit_dt}, {exit_price}, {clr_line}, 2, STYLE_SOLID, false);')

            # SL dashed line
            lines.append(f'   DrawTrendLine(chart, "{base}_SL", {entry_dt}, {sl}, {exit_dt}, {sl}, CLR_SL, 1, STYLE_DOT, true);')

            # TP dashed line
            lines.append(f'   DrawTrendLine(chart, "{base}_TP", {entry_dt}, {tp}, {exit_dt}, {tp}, CLR_TP, 1, STYLE_DOT, true);')

            # Entry arrow
            lines.append(f'   DrawArrow(chart, "{base}_ENTRY", {entry_dt}, {entry_price}, {clr_entry}, {arrow_entry}, 2);')

            # Exit marker
            lines.append(f'   DrawArrow(chart, "{base}_EXIT", {exit_dt}, {exit_price}, {clr_exit}, 251, 2);')

            # Risk zone rectangle (entry to SL)
            lines.append(f'   DrawRect(chart, "{base}_ZONE", {entry_dt}, {entry_price}, {exit_dt}, {sl}, {clr_zone}, true);')

            # Label
            lines.append(f'   DrawText(chart, "{base}_LBL", {entry_dt}, {entry_price}, "{label}", {clr_entry}, 8);')

            lines.append("")

        lines.append("}")
        lines.append("")

    # ── OnStart ──
    lines.append("//+------------------------------------------------------------------+")
    lines.append("void OnStart()")
    lines.append("{")
    lines.append("   int plotted = 0;")
    lines.append("   int failed  = 0;")
    lines.append("")

    # Try multiple symbol suffixes for Exness
    lines.append('   // Symbol suffix detection for Exness')
    lines.append('   string suffixes[] = {"", "m", ".m", "_i", "z"};')
    lines.append("")

    for pair, trades in filtered.items():
        func_name = f"PlotTrades_{pair}"
        lines.append(f'   // ── {pair} ({len(trades)} trades) ──')
        lines.append("   {")
        lines.append(f'      string baseSym = "{pair}";')
        lines.append("      string sym = \"\";")
        lines.append("      for(int s = 0; s < ArraySize(suffixes); s++)")
        lines.append("      {")
        lines.append("         string candidate = baseSym + suffixes[s];")
        lines.append("         if(SymbolSelect(candidate, true))")
        lines.append("         {")
        lines.append("            sym = candidate;")
        lines.append("            break;")
        lines.append("         }")
        lines.append("      }")
        lines.append('      if(sym == "")')
        lines.append("      {")
        lines.append(f'         Print("SKIP {pair}: symbol not found");')
        lines.append(f"         failed += {len(trades)};")
        lines.append("      }")
        lines.append("      else")
        lines.append("      {")
        lines.append("         long chart = OpenOrFindChart(sym);")
        lines.append("         if(chart <= 0)")
        lines.append("         {")
        lines.append(f'            Print("SKIP {pair}: cannot open chart");')
        lines.append(f"            failed += {len(trades)};")
        lines.append("         }")
        lines.append("         else")
        lines.append("         {")
        lines.append("            if(ClearOnly)")
        lines.append("            {")
        lines.append("               ClearS97Objects(chart);")
        lines.append(f'               Print("Cleared {pair}");')
        lines.append("            }")
        lines.append("            else")
        lines.append("            {")
        lines.append("               ClearS97Objects(chart);  // clear old before redraw")
        lines.append(f"               {func_name}(chart);")
        lines.append("               ChartRedraw(chart);")
        lines.append(f"               plotted += {len(trades)};")
        lines.append(f'               Print("Plotted {pair}: {len(trades)} trades");')
        lines.append("            }")
        lines.append("         }")
        lines.append("      }")
        lines.append("   }")
        lines.append("")

    lines.append('   Print("═══════════════════════════════════════════");')
    lines.append('   Print("S97 Trade Plotter complete. Plotted=", plotted, " Failed=", failed);')
    lines.append('   Print("═══════════════════════════════════════════");')
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate MQL5 script to plot S97 trades on Exness MT5 charts"
    )
    parser.add_argument("--pair", type=str, default=None,
                        help="Generate for only this pair (e.g. GBPUSD)")
    parser.add_argument("--clear", action="store_true",
                        help="Generate clear-only script")
    parser.add_argument("--mt5-data", type=str, default=None,
                        help="Path to MT5 data folder (e.g. C:\\Users\\...\\AppData\\Roaming\\MetaQuotes\\Terminal\\<ID>)")
    parser.add_argument("--install", action="store_true",
                        help="Auto-copy the .mq5 file to MT5 Scripts folder")
    args = parser.parse_args()

    # ── Load trades ──
    if not TRADES_JSON.exists():
        print(f"ERROR: trades file not found: {TRADES_JSON}")
        sys.exit(1)

    with open(TRADES_JSON, "r", encoding="utf-8") as f:
        all_trades: dict[str, list] = json.load(f)

    # ── Filter 2025-2026 trades ──
    filtered: dict[str, list] = {}
    for pair, trades in all_trades.items():
        if args.pair and pair.upper() != args.pair.upper():
            continue
        pair_trades = [
            t for t in trades
            if t["entry_time"][:4] in ("2025", "2026")
        ]
        if pair_trades:
            filtered[pair] = pair_trades

    total_trades = sum(len(v) for v in filtered.values())
    wins = sum(1 for trades in filtered.values() for t in trades if t["outcome"] == "win")
    losses = total_trades - wins

    print(f"\n{'='*60}")
    print(f"  S97 Trade Plotter — MQL5 Script Generator")
    print(f"{'='*60}")
    print(f"  Pairs : {len(filtered)}")
    print(f"  Trades: {total_trades} (2025-2026)")
    print(f"  Record: {wins}W / {losses}L")
    print()
    for p, t in filtered.items():
        pw = sum(1 for x in t if x["outcome"] == "win")
        pl = len(t) - pw
        print(f"    {p:8s}: {len(t):3d} trades  ({pw}W / {pl}L)")
    print(f"{'='*60}\n")

    # ── Generate MQL5 ──
    mql5_code = generate_mql5_script(filtered, clear_only=args.clear)

    # ── Write output ──
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_file = OUTPUT_DIR / "PlotS97Trades.mq5"
    output_file.write_text(mql5_code, encoding="utf-8")
    print(f"  Generated: {output_file}")
    print(f"  File size: {output_file.stat().st_size:,} bytes")
    print(f"  Lines:     {len(mql5_code.splitlines()):,}")

    # ── Auto-install to MT5 ──
    if args.install or args.mt5_data:
        mt5_data = args.mt5_data
        if not mt5_data:
            # Try to auto-detect MT5 data folder
            roaming = Path(os.environ.get("APPDATA", "")) / "MetaQuotes" / "Terminal"
            if roaming.exists():
                # Find the first terminal folder that has MQL5/Scripts
                for d in roaming.iterdir():
                    scripts_dir = d / "MQL5" / "Scripts"
                    if scripts_dir.exists():
                        mt5_data = str(d)
                        break

        if mt5_data:
            scripts_dest = Path(mt5_data) / "MQL5" / "Scripts"
            scripts_dest.mkdir(parents=True, exist_ok=True)
            dest_file = scripts_dest / "PlotS97Trades.mq5"
            shutil.copy2(output_file, dest_file)
            print(f"\n  Installed to: {dest_file}")
            print(f"\n  Next steps:")
            print(f"    1. Open MT5 -> Navigator -> Scripts")
            print(f"    2. Right-click 'Scripts' -> Refresh")
            print(f"    3. Find 'PlotS97Trades' and drag it onto any chart")
            print(f"    4. Click OK (ClearOnly=false to plot, true to clear)")
        else:
            print(f"\n  Could not auto-detect MT5 data folder.")
            print(f"  To install manually, copy the .mq5 file to:")
            print(f"    <MT5 Data Folder>\\MQL5\\Scripts\\PlotS97Trades.mq5")
            print(f"  (Find via: MT5 -> File -> Open Data Folder)")
    else:
        print(f"\n  To install to MT5, re-run with --install flag:")
        print(f"    python scripts/plot_s97_trades_on_mt5.py --install")
        print(f"\n  Or manually copy to: <MT5 Data Folder>\\MQL5\\Scripts\\")
        print(f"  (Find via: MT5 -> File -> Open Data Folder)")


if __name__ == "__main__":
    main()
